### ISSUE TITLE
Privex Queue Position 312 Less than Zednode

### ISSUE THREAD

**Issue by gaia** [Privex/znode-status#1]
I understand small (<10) differences in queue positions are to be expected, but why would my position be 312 ahead in Privex vs Zednode?

Thank you

**Comment by kryogenic** [comment]
Is your node qualified? Has it been paid at least once yet?

The very first payout is "special" and it's a known issue that ranks can be misleading for a node's first payout cycle.

**Comment by gaia** [comment]
Yes, there has been 1 pymt. but since a power outage at the datacenter the position queue was reset.

**Comment by kryogenic** [comment]
My only idea in that case is that Zednode incorrectly bases their queue position off of uptime. I'm not sure since I don't have the code that Zednode uses for their website, but that would be the my first guess.

**Comment by gaia** [comment]
Zednode told me they use a script provided by Zcoin Core. They also said they didn't know you guys were OSS, and that they will look into OSing their system.

Thank you for your help. I will ping back here with a result on which counter was more accurate when the payout happens.

**Comment by gaia** [comment]
here's a thought. the position difference is 303 more on zednode.

the difference between
Total Enabled ZNodes: 2482
Total Qualified ZNodes: 2163

is 319. 16 (319-303) positions is within the usual range of difference between zed & privex. the explanation could be related to this.

**on a separate note**, why is queue position calculated X out of 2482 (enabled), not X out of 2163 (qualified)?

**Comment by kryogenic** [comment]
In general, the ZCoin code uses the number of enabled nodes for queue calculations rather than the number of qualified nodes, for example the top 10% of the network is calculated as follows: `int(num_enabled/10)` Therefore we use the number of enabled nodes for the queue, meanwhile the ~300 non-qualified nodes just sit at the back and don't affect the queue position of qualified nodes.

As for the queue position script from Zcoin Core, I believe that is written by @aizensou, perhaps he can shed some light on how it works.

**Comment by gaia** [comment]
I got paid on the Privex schedule. Is it safe to assume that zednode was still running < 13.5.5 and privex was running >= 13.5.5 at the time the fork got triggered?

Because zednode stopped giving an indication of position after the fork happened and now gives about 300 positions behind Privex.

I still don't know why Zednode is reporting such a diff position, but it looks like Privex is correct and they have a problem.
